import Head from 'next/head';
import styles from '../styles/index.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>soraya benson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page">
        <h1>wut up rat bastards</h1>
      </main>
    </div>
  )
}
